name: Stress Test Runners

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    strategy:
      matrix:
        id: [1, 2, 3, 4, 5]
    steps:
      - name: Show runner ID
        run: |
          echo "Runner ID: ${{ matrix.id }}"

      - name: Simulate work
        run: sleep 60