name: Raspberry Pi Job

on:
  push:
    branches:
      - main

jobs:
  raspberry-pi-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/arm64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Show pod info
        run: |
          kubectl get pods
