name: Raspberry Pi Job

on:
  push:
    branches:
      - main

jobs:
  raspberry-pi-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show pod info
        run: |
          kubectl get pods
