name: Raspberry Pi Job

on:
  push:
    branches:
      - main

jobs:
  raspberry-pi-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          VERSION=v1.28.1
          ARCH=arm64
          echo "Downloading kubectl version $VERSION for $ARCH"
          curl -LO "https://dl.k8s.io/release/$VERSION/bin/linux/$ARCH/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Show pod info
        run: |
          kubectl get deployments -n matiasmartin-labs
